// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rffxvwbokgqvqehpgynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZnh2d2Jva2dxdnFlaHBneW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODA0NjYsImV4cCI6MjA2NTY1NjQ2Nn0.jM1hkF2gR0eOdfltvuw_RRPiSFamUz-rTrm_6JPGM1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);